# Generated by Django 5.2.11 on 2026-03-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_recipe_author_recipe_created_on_recipe_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="shortbio",
            field=models.TextField(),
        ),
    ]
