# Generated by Django 5.2.11 on 2026-03-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0006_recipeimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeimage",
            name="description",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
